name: gith
on:   
  pull_request:
    branches: ["master"]

jobs:
    memer:
      runs-on: ubuntu-latest
      permissions : write-all
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: "meme post"
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: Check out this random meme!\n\n![Meme]{https://pbs.twimg.com/media/Enm7QC7XYAEO-4L.jpg}