name: gith
on:   
  pull_request:
    branches: ["main"]

jobs:
    memer:
      runs-on: ubuntu-latest
      permissions : write-all
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Random meme
          uses: gautamkrishnar/blog-post-workflow@master 
          with:
            url: "https://meme-api.herokuapp.com/gimme" 

